### ISSUE TITLE
Template First Line Header Bug

### ISSUE THREAD

**Issue by gian-luca1416** [RoamJS/workbench#135]
The template engine works really well. However, if you have the first line of your template configured as h1 the result will be something like that:

_hashtag_ TEXT

It should be:
### TEXT

**Comment by TfTHacker** [comment]
I am going to close this out since Roam has now added native templates and we also have SmartBlocks as a more robust feature. The existing template engine in Roam42 we have had since summer will be removed since its no longer needed.

DM me on Twitter if you need any help with the new template functionality.
