### ISSUE TITLE
Keyboard layout is ignored

### ISSUE THREAD

**Issue by Mayeu** [RoamJS/workbench#175]
Hello 👋 

I tried this plugin today but I sadly can't use it because it ignores the layout of the keyboard I'm using.

In my case I use a physical QWERTY keyboard, and a variant of the Dvorak layout (Dvorak Programmer) at the OS level (macOS in my case).

For example,  my `D` key correspond to the QWERTY `H` key. Thus, if I hit `Ctrl-Shift-D` to go to my daily note in Roam, I also trigger pop-up the daily note overlay.

I assume that the issue lie in the fact that you are using keycode instead of the actual character send by the OS.

I'm sadly unsure on how to fix that in JS ¯\\\_(ツ)\_/¯

**Comment by TfTHacker** [comment]
Yes this is something I need to address. I honestly don't have any experience with this (as is now obvious :-)

The new roam42 menu provides access to a number of features without keyboard. ALso, the jump nav command seems to work in most environment and provides access to many roam42 features.

Finally deep nav can be enabled in the menu, and is activated with a simple "g" or "alt-g"

I will leave this as a bug for future fixing.

**Comment by tylerwince** [comment]
I also use Dvorak and have never noticed this as I am at a computer with an external Dvorak keyboard most of the time. Can confirm that `⌥-G` and Deep Nav works on any keyboard layout. I experienced the same issue with some of the more "regular" commands (⌃-⇧-H, etc). 

I would guess it is related to what @Mayeu suggested with keycodes vs character since it works with an external board that is setup with an alternate layout at the keyboard level instead of the OS level.

**Comment by Mayeu** [comment]
As a side note, I'm using Roam Toolkit and the VIM mode there work without any issue, could be worth checking how it's done there :)

**Comment by tylerwince** [comment]
@roamhacker 

I did some basic research this morning and it looks like the issue is the usage of `KeyboardEvent.code` instead of `KeyboardEvent.key`. The later allows for a more consistent experience across locals and keyboard types. 

Here are some docs on each: 

- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

And it looks like the part of the codebase in question is here:
https://github.com/roamhacker/roam42/blob/edee93fdc0b185aa0efb1e2a650ef1ead38dbf56/common/r42kb_lib.js#L16

**Comment by dvargasfuertes** [comment]
Roam42 Issue Log Audit - Will address with resurfaced used interest
