### ISSUE TITLE
Live Preview does not work with aliases

### ISSUE THREAD

**Issue by RoamanEmpire** [RoamJS/workbench#19]
Hovering over an alias instead of the original link does not activate the preview pop-up.
Perhaps the syntax is not properly supported yet?

**Comment by TfTHacker** [comment]
Thanks for the report. I will see what can be done about this. Can I ask you a question. The live preview gets in the way for many users. I am thinking of changing the activation behavior. So instead of just hovering over a link, you would need to press CTRL key and whatever you hover over would show the live preview. What do you think of that?

**Comment by RoamanEmpire** [comment]
I personally prefer the current approach because it has less friction. I haven't had a problem with it. For me it takes 2 seconds for the preview to show up so, in general, if it appears it's because I want it to appear. Also, I tend to use the keyboard shortcuts whenever possible, so I use the mouse only when I lose the cursor or for the live preview.
But if the live preview were to show up faster in the future, than I think it would make sense to require a key as well.

**Comment by TfTHacker** [comment]
> I personally prefer the current approach because it has less friction. I haven't had a problem with it. For me it takes 2 seconds for the preview to show up so, in general, if it appears it's because I want it to appear. Also, I tend to use the keyboard shortcuts whenever possible, so I use the mouse only when I lose the cursor or for the live preview.

DM me on twitter if you are interested in testing the new concept.
